name: Auto Get Waydroid
run-name: ${{ github.actor }} Auto Get Waydroid ğŸš€
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get
        env: 
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          # é…ç½®ç¯å¢ƒ
          sudo apt update
          sudo apt install curl git -y
          curl https://repo.waydro.id | sudo bash
          apt download waydroid python3-gbinder libgbinder libglibutil
          git clone https://gfdgd-xi:$PASSWORD@github.com/gfdgd-xi/waydroid-deb
          cd waydroid-deb
          cp ../*.deb .
          git add .
          git config --global user.email 3025613752@qq.com
          git config --global user.name gfdgd-xi
          git commit -m æ›´æ–°waydroid
          git push



      
    