name: Auto Get Waydroid
run-name: ${{ github.actor }} Auto Get Waydroid ðŸš€
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get
        env: 
          PASSWORD: ${{ secrets.PASSWORD }}
          KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
          KEY: ${{ secrets.KEY }}
        run: |
          sudo apt update
          sudo apt install apt-mirror -y
          sudo apt install curl git  aria2 gpg -y
          curl https://repo.waydro.id | sudo bash
          git clone https://gfdgd-xi:$PASSWORD@github.com/gfdgd-xi/waydroid-deb
          sudo mv waydroid-deb /waydroid-deb
          sudo cat > /etc/apt/mirror.list <<EOF
          set base_path    /waydroid-deb
          set nthreads     20
          set _tilde 0
          deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ jammy main
          clean https://repo.waydro.id/
          EOF
          sudo apt-mirror
          cd /waydroid-deb
          python3 build.py
          git add .
          git config --global user.email 3025613752@qq.com
          git config --global user.name gfdgd-xi
          git commit -m æ›´æ–°waydroid | true
          git push | true
          exit

          # é…ç½®çŽ¯å¢ƒ
          sudo apt update
          sudo apt install curl git  aria2 gpg -y
          aria2c $KEY
          gpg --import  --pinentry-mode loopback --batch --passphrase "$KEYPASSWORD"  private-file.key
          curl https://repo.waydro.id | sudo bash
          apt download waydroid python3-gbinder libgbinder libglibutil
          git clone https://gfdgd-xi:$PASSWORD@github.com/gfdgd-xi/waydroid-deb
          cd waydroid-deb
          cp ../*.deb .
          rm Packages || echo "Failed to remove packages file"
          rm Packages.gz || echo "Failed to remove packages.gz file"
          rm Release || echo "Failed to remove release file"
          rm Release.gpg || echo "Failed to remove release.gpg file"
          rm InRelease || echo "Failed to remove inrelease file"
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
          gpg --default-key "3025613752@qq.com" --batch --pinentry-mode="loopback" --passphrase="$KEYPASSWORD" -abs -o - Release > Release.gpg || error "failed to sign Release.gpg with gpg "
          gpg --default-key "3025613752@qq.com" --batch --pinentry-mode="loopback" --passphrase="$KEYPASSWORD" --clearsign -o - Release > InRelease || error "failed to sign InRelease with gpg"
          python3 build.py
          git add .
          git config --global user.email 3025613752@qq.com
          git config --global user.name gfdgd-xi
          git commit -m æ›´æ–°waydroid | true
          git push | true



      
    