name: Auto Get Waydroid
run-name: ${{ github.actor }} Auto Get Waydroid üöÄ
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get
        env: 
          PASSWORD: ${{ secrets.PASSWORD }}
          KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
          KEY: ${{ secrets.KEY }}
        run: |

          # ÈÖçÁΩÆÁéØÂ¢É
          #sudo dpkg --add-architecture i386
          #sudo dpkg --add-architecture armhf
          #sudo dpkg --add-architecture arm64
          sudo apt update | true
          sudo apt install curl git  aria2 gpg -y
          aria2c $KEY
          gpg --import  --pinentry-mode loopback --batch --passphrase "$KEYPASSWORD"  private-file.key
          curl https://repo.waydro.id | sudo bash | true
          #apt download waydroid python3-gbinder libgbinder libglibutil
          git clone https://gfdgd-xi:$PASSWORD@github.com/gfdgd-xi/waydroid-deb
          cd waydroid-deb
          # jammy
          mkdir -p jammy
          cd jammy
          sudo bash -c "echo deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ jammy main > /etc/apt/sources.list.d/waydroid.list"
          sudo apt update | true
          apt download waydroid python3-gbinder libgbinder libglibutil
          #apt download waydroid:i386 python3-gbinder:i386 libgbinder:i386 libglibutil:i386
          #apt download waydroid:armhf python3-gbinder:armhf libgbinder:armhf libglibutil:armhf
          #apt download waydroid:arm64 python3-gbinder:arm64 libgbinder:arm64 libglibutil:arm64
          bash ../mirror.sh
          # Ê∫êÁ†Å
          mkdir -p ../source
          cd ../source 
          apt source waydroid python3-gbinder libgbinder libglibutil
          # focal
          mkdir -p ../focal
          cd ../focal
          sudo bash -c "echo deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ focal main > /etc/apt/sources.list.d/waydroid.list"
          sudo apt update
          apt download waydroid python3-gbinder libgbinder libglibutil
          bash ../mirror.sh
          # bullseye
          mkdir -p ../bullseye
          cd ../bullseye
          sudo bash -c "echo deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ bullseye main > /etc/apt/sources.list.d/waydroid.list"
          sudo apt update
          apt download waydroid python3-gbinder libgbinder libglibutil
          bash ../mirror.sh
          # bookworm
          mkdir -p ../bookworm
          cd ../bookworm
          sudo bash -c "echo deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ bookworm main > /etc/apt/sources.list.d/waydroid.list"
          sudo apt update
          apt download waydroid python3-gbinder libgbinder libglibutil
          bash ../mirror.sh
          # lunar
          mkdir -p ../lunar
          cd ../lunar
          sudo bash -c "echo deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ lunar main > /etc/apt/sources.list.d/waydroid.list"
          sudo apt update
          apt download waydroid python3-gbinder libgbinder libglibutil
          bash ../mirror.sh
          # Êèê‰∫§
          cd ..
          python3 build.py
          git add .
          git config --global user.email 3025613752@qq.com
          git config --global user.name gfdgd-xi
          git commit -m Êõ¥Êñ∞waydroid | true
          git push | true



      
    